import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  {
    id: "abPDp1VUaf4",
    orientation: "vertical",
    video_title: "Fast-Paced Narrative (778K+ Insta Views) | High-Retention Edit",
    video_description:
      "Exploded on Instagram Reels with 778K+ organic views and 26.4K+ likes! A fast-paced, highly engaging podcast short for GrowthMiles breaking down the NDA's landslide victory in Bihar, featuring Mrityunjay Sharma. Edited for maximum retention and impact.",
    tags: ["Podcast Short", "Viral on Insta", "Political Analysis", "Fast Paced", "Shorts", "Reels"],
    cover_image: "abPDp1VUaf4",
    publish_date: "2026-01-16",
    position :4,
    client_name: "GrowthMiles",
    client_image: "/companies/growthmiles.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/abPDp1VUaf4",
    insta_link: "https://www.instagram.com/p/DTk5vjQkufV/",
    project_images: [],
    category: ["Shorts","Viral"],
    duration: "0:39",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "mgfe3feozOM",
    orientation: "vertical",
    video_title: "Viral Podcast Short (802K+ Insta Views) | Dynamic Pacing & Captions",
    video_description:
      "🔥 Generated 802K+ organic views and 17.4K+ likes on Instagram Reels! Crafted to maximize viewer retention using aggressive pacing, dynamic text animations, and perfect audio-sync. The edit focuses on a strong hook and fast-paced cuts to keep the audience engaged till the very last second.",
    tags: ["Podcast Short", "Viral on Insta", "Fast Paced", "Shorts", "Reels"],
    cover_image: "mgfe3feozOM",
    publish_date: "2026-02-09",
    position: 5,
    client_name: "GrowthMiles",
    client_image: "/companies/growthmiles.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/wBrkYeMlh1U",
    insta_link: "https://www.instagram.com/p/DUh_Yc_EuR0/",
    project_images: [],
    category: ["Shorts","Viral"],
    duration: "0:26",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "2VXCtthhcb0",
    orientation: "vertical",
    video_title: "Political Podcast Edit | Dynamic Visual Storytelling",
    video_description:
      "A highly engaging political analysis short edited for GrowthMiles featuring Mrityunjay Sharma. Focused on clean storytelling using dynamic visual cutouts (like the glowing PM Modi effect), smooth transitions, and precise audio-sync to break down complex political narratives. Crafted to make deep political insights visually appealing.",
    tags: ["Podcast Short", "Visual Storytelling", "Political Analysis", "Dynamic Cutouts", "Motion Graphics", "Shorts", "Reels"],
    cover_image: "2VXCtthhcb0",
    position: 6,
    publish_date: "2026-01-18",
    client_name: "GrowthMiles",
    client_image: "/companies/growthmiles.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/2VXCtthhcb0",
    insta_link: "https://www.instagram.com/p/DTo4KRiEuFa/",
    project_images: [],
    category: ["Shorts"],
    duration: "0:44",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "LMwXkbRuAJ8",
    orientation: "vertical",
    video_title: "The Contradiction Hook (150K+ Insta Views)",
    video_description:
      "🔥 Generated 150K+ organic views on Instagram by engineering a high-retention 'Contradiction Hook'. I strategically placed a famous clip of Akshay Kumar at the very start, immediately followed by the guest countering his exact point. This manufactured debate instantly stops the scroll, creates curiosity, and forces the viewer to watch the entire breakdown.",
    tags: ["Podcast Short", "Contradiction Hook", "High Retention", "150K+ Views", "Audience Psychology", "Shorts", "Reels"],
    cover_image: "LMwXkbRuAJ8",
    position: 7,
    publish_date: "2025-12-25",
    client_name: "GrowthMiles",
    client_image: "/companies/growthmiles.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/LMwXkbRuAJ8",
    insta_link: "https://www.instagram.com/p/DSjMUiPCLRW/",
    project_images: [],
    category: ["Shorts","Viral"],
    duration: "0:44",
    software_used: ["Premiere Pro"],
  },
  {
    id: "0rtruoHRSPk",
    orientation: "vertical",
    language: "english",
    video_title: "2D Animated Commercial | The 'Problem-Solution' Hook",
    video_description:
      "A 100% custom 2D animated ad for a Canadian brand. Leveraged a strong 'problem-solution' hook—visualizing a snow-blocked driveway before revealing a fast, satisfying fix—to grab attention and drive local leads.",
    tags: ["Motion Graphics", "Commercial Ad", "2D Animation", "Problem-Solution", "Shorts", "Reels"],
    cover_image: "0rtruoHRSPk",
    position: 11,
    publish_date: "2025-12-03",
    client_name: "Snow Bros",
    client_image: "/companies/snowbros.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/0rtruoHRSPk",
    insta_link: "",
    project_images: [],
    category: ["Shorts","Motion Graphics"],
    duration: "0:14",
    software_used: ["After Effects"],
  },
  {
      id: "ofEe2gNUFPo",
      orientation: "vertical",
      video_title: "119K+ Insta Views: Emotional Podcast Storytelling",
      video_description: "Edited a raw, highly emotional podcast short for GrowthMiles featuring actor Sanjeev Sharma discussing the harsh realities of Bollywood. Focused on slow pacing, deep sound design, and impactful cuts to ensure the audience truly 'feels' the weight of the topic. Organically generated 119K+ views on Instagram and 15K+ on YouTube.",
      tags: ["Podcast Short", "Emotional Storytelling", "High Retention", "Bollywood"],
      cover_image: "ofEe2gNUFPo",
      position: 13,
      publish_date: "2026-01-15", 
      client_name: "GrowthMiles",
      client_image: "/companies/growthmiles.png", 
      client_feedback: "",
      video_link: "https://www.youtube.com/shorts/ofEe2gNUFPo",
      insta_link: "https://www.instagram.com/reel/DTkEzCLkpOC/", 
      project_images: [],
      category: ["Shorts","Viral"],
      duration: "0:59", 
      software_used: ["Premiere Pro", "After Effects"],
    },
    {
      id: "5y9i1k4ZywQ",
      orientation: "vertical",
      video_title: "245K+ Insta Views: Luxury Car Culture & Trends",
      video_description: "Edited a high-performing podcast short for GrowthMiles discussing luxury car choices, status, and street culture (Audi vs BMW vs Mercedes). Leveraged fast-paced visual pop-ups, dynamic pacing, and engaging storytelling to capture the audience. Organically drove over 245K views on Instagram.",
      tags: ["Podcast Short", "Luxury Lifestyle", "Viral Edit", "High Retention"],
      cover_image: "5y9i1k4ZywQ", 
      position: 18,
      publish_date: "2026-02-10",
      client_name: "GrowthMiles",
      client_image: "/companies/growthmiles.png", 
      client_feedback: "",
      video_link: "https://www.youtube.com/shorts/5y9i1k4ZywQ",
      insta_link: "https://www.instagram.com/reel/DUlRr93Ery0/",
      project_images: [],
      category: ["Shorts", "Viral"],
      duration: "0:45", 
      software_used: ["Premiere Pro", "After Effects"], 
    },
    {
      id: "jlhHfb3jKas",
      orientation: "vertical",
      video_title: "278K+ Insta Views: Dark Psychology & Shock Hooks",
      video_description: "Edited a highly engaging, dark-themed podcast short for GrowthMiles exploring taboo and mystical topics (Energy/Vashikaran). Leveraged 'shock value' hooks, intense color grading, and moody sound design to instantly grab attention. Organically crossed over 278K views on Instagram.",
      tags: ["Podcast Short", "Viral Edit", "Shock Hook", "Dark Theme"],
      cover_image: "jlhHfb3jKas", 
      position: 12,
      publish_date: "2025-12-08", 
      client_name: "GrowthMiles",
      client_image: "/companies/growthmiles.png", 
      client_feedback: "",
      video_link: "https://youtube.com/shorts/jlhHfb3jKas",
      insta_link: "https://www.instagram.com/reel/DSAmizaEqqJ/", 
      project_images: [],
      category: ["Shorts", "Viral"],
      duration: "0:34", 
      software_used: ["Premiere Pro", "After Effects"], 
    },
    {
      id: "yx5n69J4H4o",
      orientation: "vertical",
      video_title: "82K+ Views: Visualizing Diet Myths",
      video_description: "Edited a viral podcast short for GrowthMiles breaking down popular Indian diet myths. Designed engaging visual pop-ups (like custom food plate cutouts) and bold, dynamic captions to retain attention on a controversial topic. Organically drove over 82.8K views on Instagram.",
      tags: ["Podcast Short", "Visual Hooks", "Viral Edit", "Health & Fitness"],
      cover_image: "yx5n69J4H4o",
      position: 19,
      publish_date: "2025-12-27", 
      client_name: "GrowthMiles",
      client_image: "/companies/growthmiles.png", 
      client_feedback: "",
      video_link: "https://www.youtube.com/shorts/yx5n69J4H4o",
      insta_link: "https://www.instagram.com/reel/DSwL3xeEvZP/",
      project_images: [],
      category: ["Shorts","Viral"],
      duration: "0:48", 
      software_used: ["Premiere Pro"],
    },
  {
    id: "2A8Ku3dNwOM",
    orientation: "vertical",
    video_title: "Motion Graphics Promo | Service Explainer",
    video_description:
      "High-impact 2D animated commercial crafted for Snow Bros, Canada. Focused on smooth visual transitions to clearly explain the snow removal service, ending with a strong Call-To-Action (CTA) designed to maximize local conversions.",
    tags: ["Motion Graphics", "Commercial Ad", "2D Animation", "Problem-Solution", "Shorts", "Reels"],
    cover_image: "2A8Ku3dNwOM",
    position: 31,
    publish_date: "2025-11-24",
    client_name: "Snow Bros",
    client_image: "/companies/snowbros.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/2A8Ku3dNwOM",
    insta_link: "",
    project_images: [],
    category: ["Shorts","Motion Graphics"],
    duration: "0:26",
    software_used: ["After Effects"],
  },
  {
    id: "V0Kd-2KGN7k",
    orientation: "vertical",
    language: "english",
    video_title: "Motion Graphics Promo | Service Explainer",
    video_description:
      "High-converting animated campaign for Snow Bros, Canada. Engineered for local brand awareness using fast-paced 2D transitions, bold typography, and engaging visual elements to accelerate customer acquisition for their snow removal services.",
    tags: ["Motion Graphics", "Commercial Ad", "2D Animation", "Problem-Solution", "Shorts", "Reels"],
    cover_image: "V0Kd-2KGN7k",
    position: 20,
    publish_date: "2025-11-25",
    client_name: "Snow Bros",
    client_image: "/companies/snowbros.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/V0Kd-2KGN7k",
    insta_link: "",
    project_images: [],
    category: ["Shorts", "Motion Graphics"],
    duration: "0:28",
    software_used: ["After Effects"],
  },
  {
      id: "IeI5UeTHIcU",
      orientation: "vertical",
      video_title: "454K+ Views: Emotional Storytelling (Charity vs Lifestyle)",
      video_description: "Edited a deeply emotional and highly viral podcast short for GrowthMiles. The topic highlighted the contrast between spending money on parties versus feeding people. Focused on slow, deliberate pacing and impactful typography to amplify the emotional weight. Organically crossed over 454K views on Instagram.",
      tags: ["Podcast Short", "Emotional Storytelling", "Viral Edit", "Humanity"],
      cover_image: "IeI5UeTHIcU", 
      position: 21,
      publish_date: "2026-02-17",
      client_name: "GrowthMiles",
      client_image: "/companies/growthmiles.png", 
      client_feedback: "",
      video_link: "https://www.youtube.com/shorts/IeI5UeTHIcU",
      insta_link: "https://www.instagram.com/p/DU2GL6QEtTA/",
      project_images: [],
      category: ["Shorts", "Viral"],
      duration: "0:36", 
      software_used: ["Premiere Pro", "After Effects"],
    },
    {
      id: "hgXCHXh0UvI",
      language: "english",
      orientation: "vertical",
      video_title: "154K+ Insta Views: Business & Geopolitics Storytelling",
      video_description: "Edited a high-impact podcast short for 'Nexxt in Line with Mohit Goel' discussing India's transformation from a 'scam country' to a global business hub. Focused on bold typography, fast-paced delivery, and authoritative visual storytelling to retain audience attention on a serious topic. Organically crossed 154K+ views on Instagram.",
      tags: ["Podcast Short", "Business", "Viral Edit", "Typography"],
      cover_image: "hgXCHXh0UvI", 
      position: 25,
      publish_date: "2025-10-04", 
      client_name: "Nexxt in Line",
      client_image: "/companies/nextinline.png",
      client_feedback: "",
      video_link: "https://www.youtube.com/shorts/hgXCHXh0UvI",
      insta_link: "https://www.instagram.com/p/DPY8-uBjLi3/",
      project_images: [],
      category: ["Shorts","Viral", "Podcast"],
      duration: "0:28",
      software_used: ["Premiere Pro", "After Effects"],
    },
    {
      id: "LHJ0uVh9OBM",
      orientation: "vertical",
      video_title: "Education System Restored: Social Impact Edit",
      video_description: "Edited an informative podcast short for 'Nexxt in Line with Mohit Goel' highlighting the transformation of government schools and digital classrooms in UP. Used clean typography, relevant B-rolls, and engaging pacing to deliver a strong narrative about grassroots leadership and education reform.",
      tags: ["Podcast Short", "Social Impact", "Education", "Political"],
      cover_image: "LHJ0uVh9OBM", 
      position: 28,
      publish_date: "2025-09-25",
      client_name: "Nexxt in Line",
      client_image: "/companies/nextinline.png",
      client_feedback: "",
      video_link: "https://www.youtube.com/shorts/LHJ0uVh9OBM",
      insta_link: "https://www.instagram.com/p/DPBqPTuib9l/",
      project_images: [],
      category: ["Shorts", "Podcast"],
      duration: "0:22",
      software_used: ["Premiere Pro", "After Effects"],
    },
    {
      id: "kz_IXj43Tj4", 
      orientation: "vertical",
      video_title: "Social Impact Edit: Is UP Safe for Women?",
      video_description: "Edited a highly impactful and sensitive podcast short for 'Nexxt in Line with Mohit Goel' discussing the critical social issue of women's safety in UP. Focused on powerful visual storytelling, compelling B-rolls, and a serious tonal pacing to address heavy subjects effectively.",
      tags: ["Podcast Short", "Social Issue", "Documentary Style", "Visual Storytelling"],
      cover_image: "kz_IXj43Tj4", 
      position: 30,
      publish_date: "2025-08-15",
      client_name: "Nexxt in Line",
      client_image: "/companies/nextinline.png", 
      client_feedback: "",
      video_link: "https://www.youtube.com/shorts/kz_IXj43Tj4",
      insta_link: "",
      project_images: [],
      category: ["Shorts", "Podcast"],
      duration: "0:27", 
      software_used: ["Premiere Pro", "After Effects"],
    },
    {
      id: "jnhtKAEoIwA", 
      orientation: "vertical",
      language: "english",
      video_title: "PepsiCo India - Corporate Short",
      video_description: "A highly engaging vertical short crafted for PepsiCo India's LinkedIn page. Focused on clean pacing and professional corporate storytelling.",
      tags: ["Corporate Short", "PepsiCo", "Interview", "Professional"],
      cover_image: "jnhtKAEoIwA", 
      position: 31,
      publish_date: "2026-01-14",
      client_name: "PepsiCo India",
      client_image: "/companies/pepsico.png", 
      client_feedback: "",
      video_link: "https://www.youtube.com/shorts/jnhtKAEoIwA",
      insta_link: "https://www.instagram.com/p/DTfFobekhKA/",
      project_images: [],
      category: ["Shorts", "Podcast"],
      duration: "0:42", 
      software_used: ["Premiere Pro"],
    },
    {
      id: "H4iwKZSO-Cg", 
      orientation: "vertical",
      language: "english",
      video_title: "PepsiCo India - Corporate Short",
      video_description: "A highly engaging vertical short crafted for PepsiCo India's LinkedIn page. Focused on clean pacing and professional corporate storytelling.",
      tags: ["Corporate Short", "PepsiCo", "Interview", "Professional"],
      cover_image: "H4iwKZSO-Cg", 
      position: 32,
      publish_date: "2025-08-25",
      client_name: "PepsiCo India",
      client_image: "/companies/pepsico.png", 
      client_feedback: "",
      video_link: "https://youtube.com/shorts/H4iwKZSO-Cg",
      insta_link: "https://www.instagram.com/p/DNx4JUP2kO9/",
      project_images: [],
      category: ["Shorts", "Podcast"],
      duration: "1:00", 
      software_used: ["Premiere Pro"],
    },
    {
      id: "dqIvZRIW4-0", 
      orientation: "vertical",
      language: "english",
      video_title: "Quantum Shift - Corporate Short",
      video_description: "A highly engaging vertical short crafted for Quantum Shift with Dr Saloni Singh. Focused on clean pacing and professional corporate storytelling.",
      tags: ["Corporate Short", "Interview", "Professional"],
      cover_image: "dqIvZRIW4-0", 
      position: 33,
      publish_date: "2025-09-03",
      client_name: "Quantum Shift",
      client_image: "/companies/quantumshift.png", 
      client_feedback: "",
      video_link: "https://youtube.com/shorts/dqIvZRIW4-0",
      insta_link: "https://www.instagram.com/p/DOJFdzVk1Gs/",
      project_images: [],
      category: ["Shorts", "Podcast"],
      duration: "0:33", 
      software_used: ["Premiere Pro"],
    },
    {
      id: "0pf_aNHb1Hs",
      language: "english",
      orientation: "vertical",
      video_title: "Corporate Interview Edit | Tech & Education",
      video_description: "Edited a clean, professional interview short for Newton School of Technology featuring an intern's conversation with the CTO of 30 Sundays. Focused on sharp pacing, professional typography, and crisp audio to make corporate/educational content highly engaging for students and tech professionals.",
      tags: ["Corporate Interview", "Educational", "Podcast Short", "Clean Edit"],
      cover_image: "0pf_aNHb1Hs", 
      position: 26,
      publish_date: "2025-08-11", 
      client_name: "Newton School of Technology",
      client_image: "/companies/newtonschool.png",
      client_feedback: "",
      video_link: "https://www.youtube.com/shorts/0pf_aNHb1Hs",
      insta_link: "https://www.instagram.com/p/DNOH6PYSFAI/",
      project_images: [],
      category: ["Shorts", "Corporate"],
      duration: "0:50", 
      software_used: ["Premiere Pro", "After Effects"],
    },
  {
      id: "dXgT-_74-hc",
      orientation: "vertical",
      video_title: "Visualizing The Unseen (Spiritual Hook)",
      video_description: "Edited a deep, spiritual podcast short for GrowthMiles exploring the concept of 'Life between Death and Rebirth'. Crafted heavy custom visuals—like the 'Heaven vs. Hell' judgment scene—to turn a highly abstract, philosophical concept into a visually gripping and easily digestible story. Organically crossed 15K views on Instagram.",
      tags: ["Podcast Short", "Spiritual", "Visual Metaphors", "Deep Storytelling"],
      cover_image: "dXgT-_74-hc",
      position: 27,
      publish_date: "2025-12-14", 
      client_name: "GrowthMiles",
      client_image: "/companies/growthmiles.png", 
      client_feedback: "",
      video_link: "https://www.youtube.com/shorts/dXgT-_74-hc",
      insta_link: "https://www.instagram.com/p/DSQD7hGEqzc/",
      project_images: [],
      category: ["Shorts"],
      duration: "0:34", 
      software_used: ["Premiere Pro", "Photoshop", "After Effects"],
    },
  {
    id: "DV_fRkxJrkw",
    orientation: "vertical",
    language: "english",
    video_title: "Animated Product Teaser | Interactive Hook",
    video_description:
      "An experimental, fast-paced animated teaser for a perfume brand's new launch. Designed specifically to maximize audience interaction, the edit uses rapid visual clues to hint at the launch location, ending with a strong 'Guess the City' CTA to drive massive comment-section engagement.",
    tags: ["Product Teaser", "Motion Graphics", "Interactive Hook", "Brand Launch", "Shorts", "Reels"],
    cover_image: "DV_fRkxJrkw",
    position: 14,
    publish_date: "2025-09-05",
    client_name: "Perfume brand",
    client_image: "/companies/",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/DV_fRkxJrkw",
    insta_link: "",
    project_images: [],
    category: ["Shorts", "Motion Graphics"],
    duration: "0:17",
    software_used: ["After Effects"],
  },
  {
    id: "geUk0_P3E8k",
    language: "english",
    video_title: "Story-Driven Interview Edit – Newton School of Technology",
    video_description: "An engaging, narrative-focused interview edit for Newton School of Technology featuring a student's journey from cracking JEE to joining NST. Structured the storyline for maximum emotional impact and viewer retention. Utilized clean cuts, seamless audio enhancement, and dynamic pacing in Premiere Pro to build trust and effectively communicate the brand's core message.",
    tags: [ "Talking Head", "Interview Edit", "EdTech", "Storytelling", "Testimonial",],
    cover_image: "geUk0_P3E8k",
    publish_date: "2025-06-25",
    position: 15,
    client_name: "Newton School of Technology",
    client_image: "/companies/newtonschool.png",
    client_feedback: "",
    video_link: "https://youtu.be/geUk0_P3E8k",
    project_images: [],
    category: ["Talking Head", "Corporate"],
    duration: "5:53",
    software_used: ["Premiere Pro", "After Effects"],
  },
  {
    id: "8wCGtFmtYOQ",
    video_title: "Dynamic Tech Promo – Newton School of Technology",
    language: "english",
    video_description: `A highly engaging, fast-paced promotional edit for Newton School of Technology. Blended seamless cuts and dynamic pacing in Premiere Pro with custom motion graphics, text animations, and visual enhancements crafted in After Effects. The edit maintains a modern, tech-forward aesthetic designed to maximize viewer retention and effectively communicate the brand's vision.`,
    tags: ["EdTech", "Education Innovation"],
    cover_image: "8wCGtFmtYOQ",
    publish_date: "2025-08-09",
    position: 10,
    client_name: "Newton School of Technology",
    client_image: "/companies/newtonschool.png",
    client_feedback: "",
    video_link: "https://youtu.be/8wCGtFmtYOQ",
    project_images: [],
    category: ["Talking Head", "Corporate"],
    duration: "6:39",
    software_used: ["Premiere Pro", "After Effect"],
  },
  {
    id: "V_PzeAjqv8s",
    language: "english",
    video_title: "PepsiCo India – Full Corporate Video Edit",
    video_description:
      "A complete, professional video edit crafted for PepsiCo India. Managed the full end-to-end post-production workflow, focusing on seamless cuts, dynamic corporate pacing, and maintaining strict brand guidelines. The entire project was assembled, synced, and polished exclusively using Premiere Pro to deliver a clean and highly engaging final product.",
    tags: ["Corporate Video", "Professional Edit", "Brand Identity", "PepsiCo India"],
    cover_image: "V_PzeAjqv8s",
    publish_date: "2025-06-29",
    position: 22,
    client_name: "PepsiCo India",
    client_image: "/companies/pepsico.png",
    client_feedback: "",
    video_link: "https://youtu.be/V_PzeAjqv8s",
    project_images: [],
    category: ["Corporate", "Talking Head"],
    duration: "14:34",
    software_used: ["Premiere Pro"],
  },
  {
    id: "0muw9kNvAH0",
    language: "english",
    video_title: "PepsiCo India – Full Corporate Video Edit",
    video_description: `A complete, professional video edit crafted for PepsiCo India. Managed the full end-to-end post-production workflow, focusing on seamless cuts, dynamic corporate pacing, and maintaining strict brand guidelines. The entire project was assembled, synced, and polished exclusively using Premiere Pro to deliver a clean and highly engaging final product.`,
    tags: [ "Corporate Video", "Professional Edit", "Brand Identity", "PepsiCo India",],
    cover_image: "0muw9kNvAH0",
    publish_date: "2025-08-25",
    position: 23,
    client_name: "PepsiCo India",
    client_image: "/companies/pepsico.png",
    client_feedback: "",
    video_link: "https://youtu.be/0muw9kNvAH0",
    project_images: [],
    category: ["Corporate", "Talking Head"],
    duration: "13:41",
    software_used: ["Premier Pro"],
  },
  {
    id: "y16wD38s9ok",
    language: "english",
    video_title: "PepsiCo India – Full Corporate Video Edit",
    video_description: `A complete, professional video edit crafted for PepsiCo India. Managed the full end-to-end post-production workflow, focusing on seamless cuts, dynamic corporate pacing, and maintaining strict brand guidelines. The entire project was assembled, synced, and polished exclusively using Premiere Pro to deliver a clean and highly engaging final product.`,
    tags: ["Corporate Video", "Professional Edit", "Brand Identity", "PepsiCo India"],
    cover_image: "y16wD38s9ok",
    publish_date: "2025-12-26",
    position: 24,
    client_name: "PepsiCo India",
    client_image: "/companies/pepsico.png",
    client_feedback: "",
    video_link: "https://youtu.be/y16wD38s9ok",
    project_images: [],
    category: ["Corporate", "Talking Head"],
    duration: "9:21",
    software_used: ["Premiere Pro"],
  },
  {
    id: "-H5taIi6hMA",
    video_title: "Cinematic Podcast Trailer (426K+ Insta Views)",
    video_description:
      "🔥 Generated 426K+ organic views and 10.6K+ likes on Instagram Post! A high-impact cinematic trailer designed to hook viewers within the first 10 seconds...",
    tags: [
      "Cinematic Trailer", "Sound Design", "SFX", "Promo", "AI Visuals",
    ],
    cover_image: "-H5taIi6hMA",
    publish_date: "2026-02-06",
    position: 2,
    client_name: "GrothMiles",
    client_image: "/companies/growthmiles.png",
    client_feedback: "",
    video_link: "https://youtu.be/-H5taIi6hMA",
    insta_link: "https://www.instagram.com/p/DUYeG-ZEu4V/",
    project_images: [],
    category: ["Trailer", "Promo","Viral"],
    duration: "2:25",
    software_used: ["Premiere Pro, After Effects, AI Tools"],
  },
  {
    id: "rixE9B52Fa4",
    language: "english",
    video_title: "Corporate LinkedIn Trailer – PepsiCo India | Tanu Sinha",
    video_description: `A crisp corporate LinkedIn trailer crafted for PepsiCo India, featuring Tanu Sinha with clean pacing, professional transitions, and a polished tone designed for high-impact social engagement.`,
    tags: ["LinkedIn Trailer", "Corporate Video", "Personal Branding", "PepsiCo India", "Professional Edit"],
    cover_image: "rixE9B52Fa4",
    publish_date: "2025-09-24",
    position: 16,
    client_name: "PepsiCo India",
    client_image: "/companies/pepsico.png",
    client_feedback: "",
    video_link: "https://youtu.be/rixE9B52Fa4",
    project_images: [],
    category: ["Trailer", "Corporate", "Podcast", "Promo"],
    duration: "1:59",
    software_used: ["Premiere Pro"],
  },
  {
    id: "NkdV1rr7gtQ",
    language: "english",
    video_title: "Corporate LinkedIn Trailer – PepsiCo India | Souvik Sinha Roy",
    video_description: `A crisp corporate LinkedIn trailer crafted for PepsiCo India, featuring Souvik Sinha Roy with clean pacing, professional transitions, and a polished tone designed for high-impact social engagement.`,
    tags: ["LinkedIn Trailer", "Corporate Video", "Personal Branding", "PepsiCo India", "Professional Edit"],
    cover_image: "NkdV1rr7gtQ",
    publish_date: "2025-08-24",
    position: 17,
    client_name: "PepsiCo India",
    client_image: "/companies/pepsico.png",
    client_feedback: "",
    video_link: "https://youtu.be/NkdV1rr7gtQ",
    linkedin_link: "https://www.linkedin.com/posts/pepsico-india_pepsidechats-lifeatpepsicoindia-pepsicoindia-activity-7363113225715896320-f9hf?utm_source=share&utm_medium=member_desktop&rcm=ACoAAFRA8TEBwTmNVuF1uq8ZqmMhvuggKBSiwi0",
    project_images: [],
    category: ["Trailer", "Corporate", "Podcast", "Promo"],
    duration: "1:56",
    software_used: ["Premiere Pro"],
  },
  {
    id: "B0m9hn--BXo",
    video_title: "Chaat.Ca – High-Impact Promotional Motion Graphics",
    language: "english",
    video_description: `A dynamic full motion graphics promotional video created for Chat.Ca, designed with bold typography, smooth transitions, and engaging visual storytelling to drive brand awareness and digital engagement.`,
    tags: [
      "Motion Graphics", "Promotional Video", "Brand Promo", "Animated Explainer", "Digital Campaign",
    ],
    cover_image: "B0m9hn--BXo",
    publish_date: "2025-10-25",
    position: 3,
    client_name: "Chaat.CA",
    client_image: "/companies/chaatca.png",
    client_feedback: "",
    video_link: "https://youtu.be/B0m9hn--BXo",
    insta_link: "https://www.instagram.com/p/DRV-wCfDa-S/",
    project_images: [],
    category: ["Motion Graphics", "Promo"],
    duration: "0:59",
    software_used: ["After effects"],
  },
  {
    id: "JA_diJPCOW4",
    video_title: "Corporate LinkedIn Trailer – PepsiCo India | Namrata Sakia",
    language: "english",
    video_description: `A polished corporate LinkedIn trailer crafted for PepsiCo India, spotlighting Namrata Sakia’s leadership presence with clean transitions, refined pacing, and a professional visual tone tailored for high-impact social engagement.`,
    tags: [
      "LinkedIn Trailer",
      "Corporate Video",
      "PepsiCo India",
      "Professional Edit"
    ],
    cover_image: "JA_diJPCOW4",
    position: 9,
    publish_date: "2025-09-05",
    client_name: "PepsiCo India",
    client_image: "/companies/pepsico.png",
    client_feedback: "",
    video_link: "https://youtu.be/JA_diJPCOW4",
    linkedin_link: "https://www.linkedin.com/posts/pepsico-india_pepsidechats-lifeatpepsicoindia-pepsicoindia-activity-7410287129114640385-RkvK?utm_source=share&utm_medium=member_desktop&rcm=ACoAAFRA8TEBwTmNVuF1uq8ZqmMhvuggKBSiwi0",
    project_images: [],
    category: ["Trailer","Corporate", "Podcast", "Promo"],
    duration: "1:49",
    software_used: ["Premiere Pro"],
  },
  {
    id: "ppcZHepW7ak",
    video_title:
      "Podcast Trailer – Cinematic Sound-Driven Edit",
    video_description: `A high-impact podcast trailer designed to hook viewers within seconds. Crafted with cinematic pacing, dynamic transitions, immersive sound design, custom SFX layering, and dramatic music builds to create tension, emotion, and anticipation. Focused on strong storytelling and maximum audience retention.`,
    tags: ["Podcast Trailer", "Cinematic Edit", "Sound Design", "Promo"],
    cover_image: "Pjz0zoO65E0",
    position: 8,
    publish_date: "2025-12-24",
    client_name: "GrowthMiles",
    client_image: "/companies/growthmiles.png",
    client_feedback: "",
    video_link: "https://youtu.be/Pjz0zoO65E0",
    insta_link: "https://www.instagram.com/p/DSp11HkklEd/",
    project_images: [],
    category: ["Podcast", "Trailer", "Promo"],
    duration: "1:50",
    software_used: ["Premiere Pro, After Effects and Photoshop"],
  },
  {
    id: "SrHVilIDHbU",
    video_title:
      "Cinematic Podcast Trailer | Immersive Sound Design",
    video_description: `Edited a gripping, tension-filled podcast trailer featuring a lawyer discussing unauthorized police violence. Focused heavily on immersive sound design and carefully curated B-roll footage to amplify the emotional weight of the topic and instantly hook the viewer.`,
    tags: ["Podcast Trailer", "Cinematic Edit", "Sound Design", "Promo"],
    cover_image: "SrHVilIDHbU",
    position: 1,
    publish_date: "2026-02-20",
    client_name: "GrowthMiles",
    client_image: "/companies/growthmiles.png",
    client_feedback: "",
    video_link: "https://youtu.be/SrHVilIDHbU",
    insta_link: "https://www.instagram.com/p/DU_EseSEklw/",
    project_images: [],
    category: ["Podcast", "Trailer", "Promo"],
    duration: "2:35",
    software_used: ["Premiere Pro, After Effects and Photoshop"],
  },
];
